//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto2._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int LoginId { get; set; }
        public Nullable<int> HenkilöId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int AccessLevel { get; set; }
    
        public virtual Henkilöstö Henkilöstö { get; set; }
    }
}
