//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto2._2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestifkpkEntities : DbContext
    {
        public TestifkpkEntities()
            : base("name=TestifkpkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakkaat> Asiakkaat { get; set; }
        public virtual DbSet<Henkilöstö> Henkilöstö { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tilaus> Tilaus{ get; set; }
        public virtual DbSet<Tilausrivi> Tilausrivi { get; set; }
        public virtual DbSet<Tuotteet> Tuotteet { get; set; }
    }
}
