//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto2._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuotteet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuotteet()
        {
            this.Tilausrivi = new HashSet<Tilausrivi>();
        }
    
        public int tuoteId { get; set; }
        public string Kuvaus { get; set; }
        public string Määrä { get; set; }
        public string Sarjanumero { get; set; }
        public int HenkilöId { get; set; }
        public string Tuotemerkki { get; set; }
        public string Tuotemalli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tilausrivi> Tilausrivi { get; set; }
    }
}
